server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: localhost:29092

clients:
  catalog:
    url: ${CLIENTS_CATALOG_URL:http://localhost:8084}
  user:
    url: ${CLIENTS_USER_URL:http://localhost:8086}

app:
  topics:
    order-confirmed: order.confirmed
    order-confirmed-partitioned: order.confirmed.partitioned
    inventory-confirmed: inventory.confirmed
    inventory-rejected: inventory.rejected
    payment-events: payment.events

  kafka:
    # Bunları Java KafkaConfig içinde @Value ile okuyup kullanırsın (opsiyonel ama güzel pratik)
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      trusted-packages: "com.ars.*"

    producer:
      acks: all
      retries: 3
      enable-idempotence: true
      add-type-headers: false

    retry:
      # DefaultErrorHandler backoff parametreleri (DLT öncesi)
      initial-interval-ms: 500
      multiplier: 2.0
      max-interval-ms: 5000
      max-elapsed-ms: 20000

    dlt:
      suffix: ".DLT"
