server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventorydb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:inventory-dev-1}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
      missing-topics-fatal: false

app:
  topics:
    order-confirmed: order.confirmed
    order-confirmed-partitioned: order.confirmed.partitioned
    inventory-confirmed: inventory.confirmed
    inventory-rejected: inventory.rejected

clients:
  catalog:
    url: ${CLIENTS_CATALOG_URL:http://localhost:8084}
